apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        #        image: yyazi/vue_crud
        image: ghcr.io/shclub/vue3:v1
        imagePullPolicy: Always
        env:
        - name: BACKEND_API_URL
          value: "backend:8080" 
        ports:
        - containerPort: 80
