apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        imagePullPolicy: Always
        image: ghcr.io/shclub/edu12-3
        env:
        - name: BACKEND_API_URL
          value: "backend" 
        ports:
        - containerPort: 80
